create a new PR "that has everything" needed
masayyad/new_repo_rename pull request #146
Opened 2020-11-12 11:10 UTC by masayyad

what should i do to**bold**, _italic_,
 
![image](https://user-images.githubusercontent.com/60648092/98932745-95af8580-2494-11eb-9dc0-bf79463f2e8d.png)

2020-11-16 10:34 UTC, masayyad commented
adding <new> "hello" and many more

2020-11-16 10:35 UTC, masayyad commented on new file
>  hey
new comment "hello" and many more

2020-11-16 10:36 UTC, mahanoor786 reviewed
adding comment "quotes", 'single quotes', and much more

2020-11-16 10:38 UTC, masayyad reviewed
add a review comment "double", 'single' and much more

2020-11-16 10:39 UTC, masayyad reviewed
adding comment "double", 'single' and much more 
![image](https://user-images.githubusercontent.com/60648092/99243092-fdc3db80-27b4-11eb-8a22-28ce726eeb9f.png)

2020-11-16 10:46 UTC, masayyad commented
adding a comment

2020-11-16 10:47 UTC, masayyad commented
add comment

2020-11-16 10:47 UTC, masayyad commented on new file
comment

2020-11-16 13:28 UTC, masayyad commented on new file
>  hey
comm

2020-11-16 13:46 UTC, masayyad commented on new file
>  hey
add a comment

2020-11-16 13:48 UTC, masayyad commented
add some comment

2020-11-16 13:49 UTC, masayyad commented
add comment

2020-11-16 13:50 UTC, masayyad commented on new file
>  hey
add

2020-11-16 13:50 UTC, mahanoor786 reviewed
add comwmnt

2020-11-16 13:52 UTC, masayyad commented
qad ccc

2020-11-16 13:53 UTC, masayyad commented on new file
add

2020-11-16 13:53 UTC, mahanoor786 reviewed
add

2020-11-16 16:18 UTC, mahanoor786 reviewed
adding _referral_ "ffff" <gg>

2020-11-16 16:29 UTC, mahanoor786 approved these changes
approve

2020-11-20 05:09 UTC, mahanoor786 reviewed
adding comment chnage

2020-11-20 05:10 UTC, mahanoor786 reviewed
adding comment chnages

2020-11-20 05:11 UTC, mahanoor786 approved these changes
checking approval

2020-11-20 05:12 UTC, mahanoor786 requested changes
checking request chnages

2020-11-20 05:20 UTC, mahanoor786 commented
add comemnt

2020-11-20 05:20 UTC, closed without merging